//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package pkg

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigReload) DeepCopyInto(out *ConfigReload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigReload.
func (in *ConfigReload) DeepCopy() *ConfigReload {
	if in == nil {
		return nil
	}
	out := new(ConfigReload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigReload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigReloadList) DeepCopyInto(out *ConfigReloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigReload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigReloadList.
func (in *ConfigReloadList) DeepCopy() *ConfigReloadList {
	if in == nil {
		return nil
	}
	out := new(ConfigReloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigReloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigReloadSpec) DeepCopyInto(out *ConfigReloadSpec) {
	*out = *in
	out.DeploymentRef = in.DeploymentRef
	out.ConfigMapRef = in.ConfigMapRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigReloadSpec.
func (in *ConfigReloadSpec) DeepCopy() *ConfigReloadSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigReloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigReloadStatus) DeepCopyInto(out *ConfigReloadStatus) {
	*out = *in
	in.LastRolloutTime.DeepCopyInto(&out.LastRolloutTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigReloadStatus.
func (in *ConfigReloadStatus) DeepCopy() *ConfigReloadStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigReloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentRef) DeepCopyInto(out *DeploymentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentRef.
func (in *DeploymentRef) DeepCopy() *DeploymentRef {
	if in == nil {
		return nil
	}
	out := new(DeploymentRef)
	in.DeepCopyInto(out)
	return out
}
