apiVersion: configreload.example.com/v1
kind: ConfigReload
metadata:
  name: example-configreload
  namespace: default
spec:
  configmapRef:
    name: my-configmap3
    namespace: default
  deploymentRef:
    name: my-deployment
    namespace: default